UPDATE TBL_NAMAYANDE
SET TYPE_ENUM='FORUSHANDE' --KARGOZAR_HAGHIGHI,NAMAYANDE_HOGHUGHI, NAMAYANDE_HAGHIGHI, KARGOZAR_HAGHIGHI, KARGOZAR_HOGHUGHI, MOJTAMA, SHOBE, BAJE_NAMAYANDE_HOGHUGHI,ICD
WHERE TYPE='‰„«Ì‰œÂ ›—Ê‘';--OTHER TYPE REPLACE. . . 